// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABY-8Z3q7J8QEtm2kEX9zU2yK9eMJdpKQ',
    appId: '1:695711956978:web:b60808e67791b77100356b',
    messagingSenderId: '695711956978',
    projectId: 'vetra-ai-d1b75',
    authDomain: 'vetra-ai-d1b75.firebaseapp.com',
    storageBucket: 'vetra-ai-d1b75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8pmUO9PJ2SAzaf9JCfjSeanZ152PkT8',
    appId: '1:695711956978:android:0c97f1877495382200356b',
    messagingSenderId: '695711956978',
    projectId: 'vetra-ai-d1b75',
    storageBucket: 'vetra-ai-d1b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADHUReZ-_FVgxMPe87DhAJTIVWwGJ2EJs',
    appId: '1:695711956978:ios:1f58f9118acedb9a00356b',
    messagingSenderId: '695711956978',
    projectId: 'vetra-ai-d1b75',
    storageBucket: 'vetra-ai-d1b75.firebasestorage.app',
    iosBundleId: 'com.example.vetraAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADHUReZ-_FVgxMPe87DhAJTIVWwGJ2EJs',
    appId: '1:695711956978:ios:1f58f9118acedb9a00356b',
    messagingSenderId: '695711956978',
    projectId: 'vetra-ai-d1b75',
    storageBucket: 'vetra-ai-d1b75.firebasestorage.app',
    iosBundleId: 'com.example.vetraAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABY-8Z3q7J8QEtm2kEX9zU2yK9eMJdpKQ',
    appId: '1:695711956978:web:4f95e0d4fb913acd00356b',
    messagingSenderId: '695711956978',
    projectId: 'vetra-ai-d1b75',
    authDomain: 'vetra-ai-d1b75.firebaseapp.com',
    storageBucket: 'vetra-ai-d1b75.firebasestorage.app',
  );
}
